config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "home/index"
  # Routes for aboutme
  match "/aboutme", to: "aboutme#index", as: :aboutme, via: :get

  # Routes for blog
  match "/blog", to: "blog_posts#index", as: :blog_posts, via: :get
  match "/blog/:title", to: "blog_posts#show", as: :blog_post, via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId

  validates :title, presence: true
  validates :content_url, presence: true
  validates :state, inclusion: { in: %w[draft published] }
  validates :publisher, presence: true, if: :published?
  validates :published_at, presence: true, if: :published?
  validates :image_path, presence: true

  friendly_id :title, use: [:slugged]

  paginates_per 8

  def published?
    state == "published"
  end

  ##
  # Fetches the content from the github
  #
  def content
    client =
      Octokit::Client.new(
        access_token: Rails.application.credentials.gh_blog_access_token,
      )
    client.contents(
      "iamzanahoria/blog_contents",
      path: content_url,
      accept: "application/vnd.github.v3.html",
    )
  end
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController
  def index
    @time = DateTime.current
    @last_blog =
      BlogPost.where(state: "published").order("published_at DESC").first
    # Pull proyects to show at about me
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts =
      BlogPost
        .where(state: "published")
        .order("published_at DESC")
        .page(params[:page])
  end

  def show
    @blog_post = BlogPost.friendly.find params[:title]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @time = DateTime.current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/aboutme/index.html.erb
<div class="w-screen p-5 flex flex-col justify-between">
  <div class="min-h-screen flex flex-col">
    <div name="local-time" class="w-full h-fit flex-initial flex flex-row justify-between">
      <%= link_to "ZANAHOR.IO", root_path, class: "hover:text-orange-400" %>
      <%= local_time(@time) %>
    </div>
    <hr class="border border-black">
    <div name="content" class="w-full h-full py-20 flex-auto flex flex-col items-center justify-around">
      <div name="self-portrait-image" class="h-72 w-auto flex flex-col">
        <%= image_tag("me.JPG", :alt => "self-portrait", class: "max-h-full max-w-full") %>
      </div>
      <div name="Introduction message" class="h-fit text-center">
        <p class="text-5xl pb-5">
          I AM ZANAHORIA
        </p>
        <p class="text-lg">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper sapien at ultrices tempor. Aenean ac orci magna. Phasellus eleifend mauris a fringilla pretium.
          Aliquam erat volutpat. Praesent semper quis massa vitae cursus. Cras at placerat arcu. Sed tincidunt at odio nec rhoncus. Pellentesque ut vulputate leo, in fermentum elit.
          Vestibulum viverra facilisis velit sit amet rutrum. Vestibulum vehicula convallis ipsum, id aliquet ante varius a. Sed dictum aliquam lorem in blandit.
          Sed tristique faucibus massa, quis faucibus est eleifend eget. Nullam porttitor quam sit amet neque tempor placerat. Maecenas bibendum, ligula mollis malesuada tincidunt,
          urna ligula blandit justo, id molestie lectus elit vel ligula.<br/>
          !!!!Revisar redaccion (y puntuacion) de esta wea!!!<br/>
          En la seccion de BLOG suelo postear bla bla bla<br/>
          Al contrario de la seccion de SIPS&BITS donde suelo escribir pensamientos o ideas sueltas sobre lo que estoy desarrollando en ese momento, puede que no las termine desarrollando
          pero se me hace buena idea descargar esas notas de mi cabeza y plasmarlas en algun lugar.
          Ultimamente le he agarrado el gusto a la fotografia, entonces ademas de poder leer sobre mis viajes en la seccion de BLOGS quise hacer mi seccion de GALERIA para poder ver
          mis fotografias de una forma mas general.
        </p>
      </div>
      <div data-controller="scroll-to">
        <%= link_to icon('fa-solid', 'angle-down', class:'fa-2xl'), '#projects', data: { action: "click->scroll-to#scrollToSection" } %>
      </div>
    </div>
  </div>
  <div id="last-blog" data-target="scroll-to.section" class="h-fit w-full flex flex-row">
    <p class="w-1/2 text-5xl"> Blog mas reciente </p>
    <div class="w-1/2 h-96 flex flex-col justify-center items-center">
      <% if @last_blog.present?  %>
        <p class="w-fit h-fit text-3xl"><%= @last_blog.title %></p>
      <% else  %>
        <p class="w-fit h-fit text-5xl"> [Aun no hay blogs publicados] </p>
      <% end %>
    </div>
  </div>
  <div id="projects" data-target="scroll-to.section" class="h-fit w-full flex flex-col">
    <p class="text-5xl"> Proyectos </p>
    <div class=" h-96 flex flex-col justify-center items-center">
      <p class="w-fit h-fit text-5xl"> [Aqui deberian ir proyectos cool en los que este trabajando]</p>
    </div>
  </div>
  <hr class="mb-5 border border-black">
    <div name="navbar" class="w-full h-fit flex flex-row items-end justify-evenly text-xl">
      <%= link_to "BLOG", blog_posts_path, class: "hover:text-orange-400" %>
      <%= link_to "SIPS&BITS", root_path, class: "hover:text-orange-400" %>
      <%= link_to "GALERIA", root_path, class: "hover:text-orange-400" %>
      <%= link_to "SOBRE MI", aboutme_path, class: "hover:text-orange-400" %>
      <div class="flex flex-row gap-2">
        <%= link_to icon('fa-brands', 'square-github', class:'fa-2xl'), "https://github.com/iamzanahorio", :target => "_blank" %>
        <%= link_to icon('fa-brands', 'square-twitter', class:'fa-2xl'), "https://twitter.com/iamzanahorio", :target => "_blank" %>
        <%= link_to icon('fa-brands', 'square-instagram', class:'fa-2xl'), "https://www.instagram.com/iamzanahorio/", :target => "_blank" %>
      </div>
    </div>
</div>

app/views/blog_posts/index.html.haml
- if @blog_posts.empty?
  %h2 Hello world
- else
  - @blog_posts.each do |blog_post|
    .post-preview{"id": "post-preview-#{blog_post.id}"}
      = link_to blog_post_path(blog_post) do
        %h2.post-title
          = blog_post.title

        %h3.post-subtitle
          = blog_post.subtitle
    %p.post-meta
      Posted by
      = link_to blog_post.publisher, blog_post.publisher_url.presence || '#', id: 'blog-post-publisher'
      = "On #{DatetimeFormatter.format(blog_post.published_at)}"

app/views/home/index.html.erb
<div class="w-screen flex flex-row">
  <div name="banner-image" class="w-full h-screen flex flex-col p-5">
    <%= image_tag("home.JPG", :alt => "home image", class: "h-full object-cover rounded-lg") %>
  </div>
  <div class="w-full p-5 flex flex-col justify-between">
    <div name="local-time" class="w-full h-fit flex flex-row justify-between">
      <%= link_to "ZANAHOR.IO", root_path, class: "hover:text-orange-400" %>
      <%= local_time(@time) %>
    </div>
    <hr class="border border-black">
    <div name="content" class="w-full h-full flex flex-row items-center">
      <div class="h-fit">
        <p class="text-5xl">
          I<br>
          AM<br>
          ZANAHORIO
        </p>
      </div>
    </div>
    <hr class="mb-5 border border-black">
    <div name="navbar" class="w-full h-fit flex flex-row items-end justify-evenly text-xl">
      <%= link_to "BLOG", blog_posts_path, class: "hover:text-orange-400" %>
      <%= link_to "SIPS&BITS", root_path, class: "hover:text-orange-400" %>
      <%= link_to "GALERIA", root_path, class: "hover:text-orange-400" %>
      <%= link_to "SOBRE MI", aboutme_path, class: "hover:text-orange-400" %>
      <div class="flex flex-row gap-2">
        <%= link_to icon('fa-brands', 'square-github', class:'fa-2xl'), "https://github.com/iamzanahorio", :target => "_blank" %>
        <%= link_to icon('fa-brands', 'square-twitter', class:'fa-2xl'), "https://twitter.com/iamzanahorio", :target => "_blank" %>
        <%= link_to icon('fa-brands', 'square-instagram', class:'fa-2xl'), "https://www.instagram.com/iamzanahorio/", :target => "_blank" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zanahoria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="min-h-screen flex font-serif bg-yellow-50">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/blog.html.haml
!!!
%html
  %head
    %title= page_title

    = stylesheet_link_tag 'blog', media: 'all'

    = javascript_include_tag 'blog'

  %body{
    class: "#{controller_name} #{action_name} #{request.fullpath.delete("/")}"
  }
    = yield